server:
  port: 5000

webhooks:
  sonarr:
    path: /webhook/sonarr
    handler: sonarr
    # Optional: specify which api client to use for this webhook
    target_api: media_server_refresh 

  radarr:
    path: /webhook/radarr
    handler: radarr
    target_api: media_server_refresh

api_clients:
  media_server_refresh:
    url: "http://192.168.178.164:8096/Library/Refresh"
    method: POST
    headers:
      Authorization: 'MediaBrowser Token="74718914f62c426aa7de849ae2f1fdfc"'
      Content-Type: "application/json"
  
  notification_service:
    url: "https://ntfy.sh/stubenflix_alerts"
    method: POST
